pipeline {

    agent {
        docker {
            image 'python:3.12-slim'
            args '-u root'
        }
    }

    options {
        timestamps()
        ansiColor('xterm')
    }

    environment {
        APP_NAME = "Enterprise CI/CD Platform"
    }

    stages {

        stage('Checkout') {

            steps {
                checkout scm
            }
        }

        stage('Repository Info') {

            steps {
                echo "Repository checked out successfully."

                sh '''
                    pwd
                    ls -la
                '''
            }
        }

        stage('Python Version') {

            steps {
                sh '''
                    python --version
                    pip --version
                '''
            }
        }

        stage('Create Virtual Environment') {

            steps {
                sh '''
                    python -m venv venv

                    . venv/bin/activate

                    python --version
                '''
            }
        }

        stage('Install Dependencies') {

            steps {
                sh '''
                    . venv/bin/activate

                    pip install --upgrade pip

                    pip install -r requirements.txt
                '''
            }
        }

        stage('Environment Validation') {

            steps {
                sh '''
                    . venv/bin/activate

                    pip list
                '''
            }
        }

        stage('Flask Validation') {

            steps {
                sh '''
                    . venv/bin/activate

                    python -c "from app import create_app; create_app(); print('Flask Application Loaded Successfully')"
                '''
            }
        }

    }

    post {

        success {
            echo 'Pipeline completed successfully.'
        }

        failure {
            echo 'Pipeline failed.'
        }

        always {
            cleanWs()
        }

    }

}